### ISSUE TITLE
When using forgotPassword from opgsdk_lite_v1.5 the link from the email redirects to OPG website, to login 

### ISSUE THREAD

**Issue by andramarin** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#26] opened 2017-12-12 10:27 UTC
This behaviour is recent. Before, the user was redirected to a screen where he should add the new and old password. Can you make a change and redirect user to this screen. The login screen is not relevant for the user, since the OPG is used in background in the app.

**Comment by NeerajOPG** [comment] 2017-12-12 10:46
Hi @andramarin 
Thanks for reporting the issue. This is known issue for us and we are working on it.
we will fix it as soon as possible.
Issue : https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/issues/378

**Comment by NeerajOPG** [comment] 2017-12-12 12:19
Hi @andramarin 
The issue is fixed. 
If it  will not work then please clear the browser cookies. 

Please let us know if you need anything else.
Thanks

**Comment by andramarin** [comment] 2017-12-13 12:32
We tested this change, and after clearing cache the loded page has changed. 
But the password does not change, and we cannot login with the new one.

**Comment by andramarin** [comment] 2017-12-13 14:11
@NeerajOPG do you have any updates on this?

**Comment by NeerajOPG** [comment] 2017-12-14 04:52
@andramarin My sincere apologies for the delayed response. 
we are working on it and will resolve it soon. 
We will update once it is fixed.

**Comment by andramarin** [comment] 2017-12-14 06:21
That is great, thank you

**Comment by NeerajOPG** [comment] 2017-12-14 07:51
@andramarin
The issue has fixed and released.
Please test and confirm.

**Comment by NeerajOPG** [comment] 2018-01-04 11:00
It is working now so we are closing it.

**Closed by NeerajOPG** 2018-01-04 11:00 UTC
